"""Added transactions relationship

Revision ID: d876291f0a26
Revises: 
Create Date: 2023-11-19 01:12:17.307501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd876291f0a26'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'balance', ['balance_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('balance_id')

    # ### end Alembic commands ###
